Update check_dbt_job_and_return_details.yml

diff --git a/.github/workflows/check_dbt_job_and_return_details.yml b/.github/workflows/check_dbt_job_and_return_details.yml
--- a/.github/workflows/check_dbt_job_and_return_details.yml
+++ b/.github/workflows/check_dbt_job_and_return_details.yml
@@ -26,6 +26,13 @@ jobs:
           dbt_cloud_token: ${{ secrets.DBT_CLOUD_TOKEN }}
           dbt_cloud_account_id: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
           dbt_cloud_job_id: 130247
-      - name: Check outputs and modified files
+      - name: Check on dbt cloud job failures
+        if:  steps.selftest.outputs.myOutput != 'Success'
         run: |
-                    echo "${{ steps.selftest.outputs.myOutput }}"
+          echo "dbt cloud job failed or was cancelled"
+          exit 1
+      - name: Check on dbt cloud job sucess
+        if:  steps.selftest.outputs.myOutput == 'Success'
+        run: |
+          echo "dbt cloud job was sucessful"
+          exit 0
